version: '3.3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  gamepanel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - .:/capp
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    env_file:
      - /home/aminedachir/Documents/static_web/my-react-flow-app/.env
   
  frontend:
    build:
      context: ./my-react-flow-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./my-react-flow-app:/app
      - /app/node_modules
    depends_on:
      - gamepanel
    env_file:
      - /home/aminedachir/Documents/static_web/my-react-flow-app/.env