version: '3.3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  gamepanel:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "5000:5000"
  restart: unless-stopped
  volumes:
    - .:/capp
  depends_on:
    - redis
  environment:
    - FLASK_ENV=production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_DB=0
   
  frontend:
    build:
      context: ./my-react-flow-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./my-react-flow-app:/app
      - /app/node_modules
    depends_on:
      - gamepanel
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  # game:
  #   build:
  #     context: ./game
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - redis
  #   command: python game_server.py